# Generated by Django 5.0.1 on 2024-01-12 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('episodes', models.IntegerField()),
                ('my_episode', models.IntegerField()),
                ('my_rating', models.PositiveIntegerField()),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_anime_list.animetype')),
            ],
        ),
    ]
